FROM openjdk:8-jre-alpine
ARG PACKAGE_VERSION
ARG APPLICATION_NAME
ENV PACKAGE_VERSION ${PACKAGE_VERSION}
ENV APPLICATION_NAME ${APPLICATION_NAME}
COPY /target/${APPLICATION_NAME}-${PACKAGE_VERSION}.jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar
EXPOSE 8080
CMD ["sh", "-c", "java -jar ${APPLICATION_NAME}-${PACKAGE_VERSION}.jar"]
